### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by EugeneC** [comment]
Hi, @mickaelandrieu !
Thanks for your contribution.

**Comment by EugeneC** [comment]
Internal ID: BB-11668.

**Comment by yurio** [comment]
Hi, @mickaelandrieu.
Thanks for your contribution. But i close your pull request because this typo was already fixed and your pull request is no actual anymore.

**Comment by mickaelandrieu** [comment]
:+1:

**Pull request closed without merging**
