### PR TITLE
 I want to translate your project into French and Korean

### PR DESCRIPTION
**Pull request by hulyaa**
Hello I want to translate your project into French and Korean for master.new project and utopian.I wait answer quickly please

### CODE REVIEW

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocommerce.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by aalgogiver** [comment]
Hi, @hulyaa.
Please take a loook at our [documenation about application translation](https://oroinc.com/doc/orocrm/2.3/community/translations).

**Comment by hulyaa** [comment]
Thank you very much for answer quickly I signed  cla: no

**Comment by hulyaa** [comment]
Can ı start in crowdin?

**Comment by mbessolov** [comment]
@hulyaa Sure, please you can create a CrowdIn account and participate in OroCommerce translation at https://crowdin.com/project/orocommerce and https://crowdin.com/project/oro-platform

**Comment by hulyaa** [comment]
ok.thank you

**Pull request closed without merging**
